### ISSUE TITLE
Don't have subvolid 5

### ISSUE THREAD

**Issue by zarMarco** [jrabinow/snapper-rollback#2] opened 2022-02-16 17:40 UTC
Hi, I've installed this package and I tried to use with grub-btrfs for rollback, similar to opensuse. If I used old snapshot read-only, when I used snapper-rollback number of snapshot I confirmed but I had error because subvolid wasn't ID 5.

**Comment by jrabinow** [comment] 2022-02-16 23:51
Hey there, thanks for reporting. I have a hunch what's happening is that `/btrfsroot` directory can't be created because `/` is mounted read-only by grub-btrfs, but I can't be sure without more info. Could you fill out the bugreport issue template (the one you see when you create a new issue in this repo) and include the full script output in your report?

Are you able to workaround the issue you're seeing? If so, what workaround did you use? If not, could you find a read-write location on your filesystem and change `mountpoint` value in your `snapper-rollback.conf` to someplace under that read-write location?

**Comment by jrabinow** [comment] 2022-02-17 08:38
Closing as duplicate of #3

**Closed by jrabinow** 2022-02-17 08:38 UTC
