### ISSUE TITLE
[BUG] still booting read only after roll back

### ISSUE THREAD

**Issue by imthenachoman** [jrabinow/snapper-rollback#15] opened 2023-07-09 22:06 UTC
**Describe the bug**

Debian boots into read-only mode after doing rollback.

I followed the guide at https://github.com/david-cortes/snapper-in-debian-guide and everything went according to plan.

From the grub menu, I booted into a `pre` snappshot. Then I did a `sudo snapper-rollback 3` and rebooted.

I booted the default GRUB entry.

The system still booted into read only mode.

**To Reproduce**
1. boot into `pre` snapshot
2. `sudo snapper-rollback #`
3. boot default GRUB entry

**Expected behavior**
It should boot the rolled back snapshot in read+write.

**Actual behavior**
It boots into read only mode.

**Comment by jrabinow** [comment] 2023-07-10 04:39
Just to make sure I understand:
- you booted into a previous snapshot which itself is readonly
- you are running snapper-rollback from there
- when you reboot into the rootfs, the system is readonly as well?

Snapper was built by and for openSuse, then adapted by the archlinux community for arch and its subvariants. Debian support came later by a few volunteers and is quite new per my understanding.
I've never used or tested this script on Debian, and I'm unfamiliar with the guide you linked to so you're probably going to have to debug this on your own or with the guide author's help.

A few pointers:
- what is the partition layout? The subvolume layout? It should match the [ArchWiki suggested volume layout](https://wiki.archlinux.org/title/Snapper#Suggested_filesystem_layout)
- what [command-line was the kernel booted with](https://wiki.archlinux.org/title/Snapper#Suggested_filesystem_layout)?
- the way to solve this problem, like any other, is to isolate it. Will your system be rw if you're booted into your standard rootfs at the time you run the script? Will it be rw if you reboot into a different snapshot? What config do the problematic snapshots have? What happens if you boot into a non-rootfs read-write snapshot? And so on.

If all else fails, you might want to consider going with the [Spiral Linux project](https://github.com/SpiralLinux/SpiralLinux-project), which apparently does all this setup for you out of the box. This isn't an endorsement as I haven't tested the script out on Spiral either, but it might help you isolate the issue a bit further.

In any case, I'll be interested to hear what your solution was - please let me know if I can help.

**Comment by jrabinow** [comment] 2023-07-10 04:42
Just to make sure I understand:
- you booted into a previous snapshot which itself is readonly
- you are running snapper-rollback from there
- when you reboot into the rootfs, the system is readonly as well?

Snapper was built by and for openSuse, then adapted by the archlinux community for arch and its subvariants. Debian support came later by a few volunteers and is quite new per my understanding.
I've never used or tested this script on Debian, and I'm unfamiliar with the guide you linked to so you're probably going to have to debug this on your own or with the guide author's help.

A few pointers:
- what is the partition layout? The subvolume layout? It should match the [ArchWiki suggested volume layout](https://wiki.archlinux.org/title/Snapper#Suggested_filesystem_layout)
- what [command-line was the kernel booted with](https://unix.stackexchange.com/a/48602)?
- the way to solve this problem, like any other, is to isolate it. Will your system be rw if you're booted into your standard rootfs at the time you run the script? Will it be rw if you reboot into a different snapshot? What config do the problematic snapshots have? What happens if you boot into a non-rootfs read-write snapshot? And so on.

If all else fails, you might want to consider going with the [Spiral Linux project](https://github.com/SpiralLinux/SpiralLinux-project), which apparently does all this setup for you out of the box. This isn't an endorsement as I haven't tested the script out on Spiral either, but it might help you isolate the issue a bit further.

In any case, I'll be interested to hear what your solution was - please let me know if I can help.

**Comment by imthenachoman** [comment] 2023-07-10 04:51
> * you booted into a previous snapshot which itself is readonly

Yes.

> * you are running snapper-rollback from there

Yes.

> * when you reboot into the rootfs, the system is readonly as well?

Yes.

> * what is the partition layout? The subvolume layout? It should match the [ArchWiki suggested volume layout](https://wiki.archlinux.org/title/Snapper#Suggested_filesystem_layout)

Yup. Except it its `@rootfs` instead of `@`.

> * what [command-line was the kernel booted with](https://unix.stackexchange.com/a/48602)?

Looks like it is booting `ro`.

```
BOOT_IMAGE=/vmlinuz-6.1.0-10-amd64 root=UID... ro rootflags=subvol=@snapshots/6/snapshot quite
```

Now I'm wondering why. When I first installed snapper, before I did any rollback, it booted fine -- not in read only mode.

It only started doing this after I did a rollback. Suspicious.

**Comment by imthenachoman** [comment] 2023-07-10 04:53
I am going to do another fresh install, and this time I'll boot into the snapshot but not do a `snapper-rollback`. Then I'll see if it'll let me boot back normally. 

One of two things will happen:

1. It works -- means something is up with `snapper-rollback`
2. It does not work -- means the problem is with something else, not `snapper-rollback`.

**Comment by jrabinow** [comment] 2023-07-10 04:56
The issue is definitely with the rollback per your description. My question is how is the rollback configured? I'm not sure I'd pin it on the script so fast - I see your kernel cmdline is booting into a snapshot. If that's after the reboot and you're selecting the default grub menuentry, why are you booting into a snapshot?.

Before pinning the problem you're facing on anything, it's important to prove beyond a doubt the origin of the issue. It sounds like this is a very custom setup, which is fine, but it means extra care needs to be taken to isolate the problem to one of the components.

**Comment by imthenachoman** [comment] 2023-07-10 04:59
> My question is how is the rollback configured?

What exactly do you mean? Do you mean the `/etc/snapper-rollback.conf` file? It's left to defaults except for this line:

```
subvol_main = @rootfs
```

>  If that's after the reboot and you're selecting the default grub menuentry, why are you booting into a snapshot?

That is the question....

**Comment by jrabinow** [comment] 2023-07-10 05:05
The script doesn't actually touch grub or its menuentries because too much complexity. I invite you to read through the script source once and use `--dry-run` flag, but it sounds like your grub menuentries are messed up for some reason. Which makes the script here a very unlikely culprit, though it's not impossible of course.

I'll be interested to know why the default grub menuentry are pointing to a snapshot

**Comment by imthenachoman** [comment] 2023-07-10 06:13
This be strange. I did a fresh install and installed all the tools: [snapper](https://github.com/openSUSE/snapper), [grub-btrfs](https://github.com/Antynea/grub-btrfs) and [snapper-rollback](https://github.com/jrabinow/snapper-rollback).

I haven't done any rollbacks and am booting up the default grub menuentry.
 Everything works as expected. The filesystem is not read only. I can do things. 

But it still shows ro for how the kernel was booted:

```
BOOT_IMAGE=/vmlinuz-6.1.0-10-amd64 root=UID... ro rootflags=subvol=@rootfs quite
```

I am going to keep debuging this. Thanks!

**Comment by jrabinow** [comment] 2023-07-11 00:32
I'll close this issue now, but I'd be curious to know what happened. Good luck debugging!

**Closed as completed by jrabinow** 2023-07-11 00:32 UTC
Labels: bug

**Comment by imthenachoman** [comment] 2023-07-11 00:43
I fixed the issue. I did a fresh install and chnaged two things. I'm not sure which fixed the issue, but one of them did. Thank you and sorry about that.

https://github.com/david-cortes/snapper-in-debian-guide/issues/2#issuecomment-1629926033 if you're curious what I did.

**Comment by jrabinow** [comment] 2023-07-11 05:53
Thanks for circling back with the explanation!
