### ISSUE TITLE
I am left without network device after rollback

### ISSUE THREAD

**Issue by d4rios** [jrabinow/snapper-rollback#20] opened 2024-04-03 11:55 UTC
**Describe the bug**
After some time with my newly installed archlinux, I am about to do a complete system upgrade with "pacman -Syu". If I then decide to rollback to a previous snapshot ("*** Base ***), after booting the system I find that I have no network. I check my network devices and only find the "loopback" interface but not my network card. I read the files inside the "/sys/class/net" directory and it is empty. 

Is this normal or am I doing something wrong?

**To Reproduce**
- System full upgrade with "pacman -Syu"
- Rollback to previous snapshot "snapper-rollback 1" and after CONFIRM --> reboot 
- After rollback I have no network

**Expected behavior**
I hope to have the network available and to be able to use it.

**Actual behavior**
I have no network

**Screenshots**
![Screenshot_2024-04-03-13-31-44_24609](https://github.com/jrabinow/snapper-rollback/assets/80931135/405d5623-8a0a-4386-aaca-951bd795ae65)
![Screenshot_2024-04-03-13-37-22_6837](https://github.com/jrabinow/snapper-rollback/assets/80931135/45bcd6a4-1471-48a4-a205-e589603332f8)
![Screenshot_2024-04-03-13-53-23_8593](https://github.com/jrabinow/snapper-rollback/assets/80931135/7f465215-f019-46f2-ad7c-b3b303c67697)
![Screenshot_2024-04-03-13-52-56_22105](https://github.com/jrabinow/snapper-rollback/assets/80931135/8b92a584-cb35-4499-b906-b5dd44475eb5)
![Screenshot_2024-04-03-13-54-48_21570](https://github.com/jrabinow/snapper-rollback/assets/80931135/5e2131e8-3bc4-418f-9e5a-802d6073ad4f)

**Software**
uname -a: Linux archbox 6.8.2-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:20 +0000 x86_64 GNU/Linux
Snapper version: snapper 0.10.7
snapper-rollback version: 1.0.1
snap-pac version: 3.0.1.2
grub-btrfs version: 4.13.1

**Comment by jrabinow** [comment] 2024-04-03 17:12
> Is this normal

Clearly not.

> or am I doing something wrong?

Not necessarily either.

I'm not sure why your network interfaces broke, then again that's very much out of scope of what this script does. The wiki recommends [reading the announcements mailing list](https://wiki.archlinux.org/title/system_maintenance#Read_before_upgrading_the_system) before upgrading, I'm not sure if that could help you narrow down what the issue is here.

Another avenue you might want to explore is getting an actual repro case. Anyone else running `pacman -Syu` followed by a rollback is unlikely to have the same problem. Having an answer to "If you needed to repro this on a different machine, how would you do so?" would help you identify the root cause.
That being said, there's probably more straightforward ways to go about things [1](https://linuxconfig.org/how-to-rollback-pacman-updates-in-arch-linux) [2](https://bbs.archlinux.org/viewtopic.php?id=201517)

Good luck!

**Closed as not planned** 2024-04-12 16:50 UTC
